language: ruby
rvm:
  - 2.2.2
  - 2.3.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx
env:
  - "RAILS_VERSION=master"
  - "RAILS_VERSION=5.0.0"
  - "RAILS_VERSION=5.0.0.1"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - env: RAILS_VERSION=master
sudo: false
