language: ruby
rvm:
  - 2.2.5
  - 2.3.0
  - ruby-head
  - jruby-9.0.5.0
  - jruby-head
  - rbx-2.2.7
env:
  - "RAILS_VERSION=master"
  - "RAILS_VERSION=5.0.0"
  - "RAILS_VERSION=5.0.0.1"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - env: RAILS_VERSION=master
sudo: false
